version: "3.1"

services:
  front:
    build: apps/front
    restart: always
    depends_on:
      - mongo
    environment:
      - "HOST_IP=${HOST_IP}"
    volumes:
      - "./www:/www"

  auth:
    build: apps/auth
    restart: always
    depends_on:
      - mongo

  nginx:
    build: nginx
    restart: always
    depends_on:
      - front
      - auth
    ports:
      - "8080:80"
    volumes:
    - "./www:/www:ro"

  mongo:
    image: mongo:4.1.4-xenial
    restart: always
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=hosting"
      - "MONGO_INITDB_ROOT_PASSWORD=hosting"
  dns:
    build: dns
    restart: always
    ports:
      - "53:53"
      - "53:53/udp"
    environment:
    - "HOST_IP=${HOST_IP}"
